[package]
name = "matchit"
version = "0.3.0"
license = "MIT"
authors = ["ibraheem <ibrah1440@gmail.com>"]
edition = "2018"
description = "A high performance URL path (route) matcher based on a radix tree."
categories = ["network-programming", "algorithms"]
keywords = ["path", "tree", "radix", "match", "url"]
repository = "https://github.com/ibraheemdev/matchit"
readme = "README.md"

[dependencies]
