[package]
name = "turbo-rs"
version = "0.0.0"
license = "MIT"
authors = ["ibraheem <ibrah1440@gmail.com>"]
edition = "2018"
description = "A fast lightweight rust framework built on top of hyper (wip)."
repository = "https://github.com/ibraheemdev/turbo-rs/"
readme = "README.md"

[dependencies]
futures = "0.3.6"
hyper = "0.13.8"
